### ISSUE TITLE
CALIDAD Y DISTINTOS TIPOS DE PRUEBA

### ISSUE THREAD

**Issue by Elisahadad** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Elisahadad#1]
[CALIDAD Y DISTINTOS TIPOS DE PRUEBA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Elisahadad/files/15475555/CALIDAD.Y.DISTINTOS.TIPOS.DE.PRUEBA.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
